[package]
name = "st7920"
version = "0.1.0"
authors = ["Riccardo Ripanti <riccardo.ripanti01@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
embedded-hal = "1.0.0"
log = "0.4.21"
fugit = "0.3.7"

[dependencies.either]
version = "1.13.0"
default-features = false
