[package]
name = "st7920"
version = "0.1.0"
authors = ["Riccardo Ripanti <riccardo.ripanti01@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
esp-hal = { version = "0.19.0", optional = true }
fugit = { version = "0.3.7", optional = true }

# esp-println = { version = "0.10.0", features = ["esp32", "log"], optional = true }
# log = { version = "0.4.21", optional = true  }

[features]
esp = ["dep:esp-hal", "dep:fugit"]
